title: Teach a machine
hero_image: images/banner.png
description: Teach a computer to tell you how many fingers you are holding up!
version: 1
listed: false
copyedit: true
last_tested: "2024-05-06"
steps:
  - 
    title: Що ти зробиш
  - 
    title: Add images
    completion:
      - engaged
  - 
    title: Навчи і протестуй
    completion:
      - internal
  - 
    title: Завдання
    challenge: true
  - 
    title: Швидкий тест
    completion:
      - external
