title: Навчи машину
hero_image: images/banner.png
description: Навчи компʼютер розрізняти, скільки пальців ти показуєш!
version: 1
listed: false
copyedit: true
last_tested: "2024-05-06"
steps:
  - 
    title: Що ти зробиш
  - 
    title: Додай зображення
    completion:
      - engaged
  - 
    title: Навчи і протестуй
    completion:
      - internal
  - 
    title: Завдання
    challenge: true
  - 
    title: Що ти тепер вмієш?
    completion:
      - external
