title: Teach a machine
hero_image: images/banner.png
description: Teach a computer to tell you how many fingers you are holding up!
version: 1
listed: false
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: Wat ga je maken
  - 
    title: Add images
    completion:
      - engaged
  - 
    title: Trainen en testen
    completion:
      - internal
  - 
    title: Uitdaging
    challenge: true
  - 
    title: Wat kun je nu doen?
    completion:
      - internal
