title: Teach a machine
hero_image: images/banner.png
description: Teach a computer to tell you how many fingers you are holding up!
version: 1
listed: false
copyedit: false
last_tested: "2024-05-24"
steps:
  - title: What you will make
  - title: Train the model
  - title: Step-by-step guide
  - title: What can I do now?