title: Create an image classifier
hero_image: images/banner.png
description: Create a machine learning model trained on images to build a classifier that can detect what is shown to a webcam
version: 1
listed: false
copyedit: false
last_tested: "2024-05-24"
steps:
  - title: What you will make
  - title: Train the model
  - title: Step by step guide
  - title: What can I do now?