title: Enseñar a una máquina
hero_image: images/banner.png
description: '¡Enséñele a una computadora a decirle cuántos dedos tiene levantados!'
version: 1
listed: true
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: Lo que harás
  - 
    title: Añadir imágenes
    completion:
      - comprometido
  - 
    title: Entrenar y probar
    completion:
      - interno
  - 
    title: Desafío
    challenge: true
  - 
    title: '¿Qué puedes hacer ahora?'
    completion:
      - external
