title: 機械に教える
hero_image: images/banner.png
description: 何本の指を上げているかをコンピューターに教えましょう！
version: 1
listed: true
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: はじめに
  - 
    title: 画像を追加する
    completion:
      - engaged
  - 
    title: トレーニングとテスト
    completion:
      - internal
  - 
    title: チャレンジ
    challenge: true
    completion:
      - external
