---
title: Enséñale a una máquina
hero_image: images/banner.png
description: '¡Enséñale a una computadora a decirte cuántos dedos tienes levantados!'
version: 1
listed: true
copyedit: true
last_tested: "2024-05-24"
steps:
  - title: Lo que harás
  - title: Añadir imágenes
    completion:
      - engaged
  - title: Entrena y pueba
    completion:
      - internal
  - title: Desafío
    challenge: true
    completion:
      - external
