title: Teach a machine
hero_image: images/banner.png
description: Teach a computer to tell you how many fingers you are holding up!
version: 1
listed: true
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: Εισαγωγή
  - 
    title: Add images
    completion:
      - engaged
  - 
    title: Train and test
    completion:
      - internal
      - external
  - 
    title: Πρόκληση
    challenge: true
  - 
    title: Αναστοχασμός
