title: Teach a machine
hero_image: images/banner.png
description: Teach a computer to tell you how many fingers you are holding up!
version: 1
listed: false
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Add images
    completion:
      - engagé
  - 
    title: Entraîner et tester
    completion:
      - interne
  - 
    title: Défi
    challenge: true
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - internal
