title: Apprendre à une machine
hero_image: images/banner.png
description: Apprends à un ordinateur à te dire combien de doigts tu tiens en l'air !
version: 1
listed: false
copyedit: true
last_tested: "2024-05-24"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Ajouter des images
    completion:
      - engagé
  - 
    title: Entraîner et tester
    completion:
      - interne
  - 
    title: Défi
    challenge: true
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - internal
