title: Insegna a una macchina
hero_image: images/banner.png
description: Insegna a un computer a dirti quante dita stai alzando!
version: 1
listed: true
copyedit: true
last_tested: "2024/05/24"
steps:
  - 
    title: Cosa creerai
  - 
    title: Aggiungi immagini
    completion:
      - fatto
  - 
    title: Addestra e testa
    completion:
      - interno
  - 
    title: Sfida
    challenge: true
    completion:
      - external
